// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: business/general_response.proto

#ifndef PROTOBUF_business_2fgeneral_5fresponse_2eproto__INCLUDED
#define PROTOBUF_business_2fgeneral_5fresponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "base/header.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_business_2fgeneral_5fresponse_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsGeneralResponseImpl();
void InitDefaultsGeneralResponse();
inline void InitDefaults() {
  InitDefaultsGeneralResponse();
}
}  // namespace protobuf_business_2fgeneral_5fresponse_2eproto
namespace xsproto {
namespace communication {
class GeneralResponse;
class GeneralResponseDefaultTypeInternal;
extern GeneralResponseDefaultTypeInternal _GeneralResponse_default_instance_;
}  // namespace communication
}  // namespace xsproto
namespace xsproto {
namespace communication {

enum GeneralResponse_State {
  GeneralResponse_State_FAILED = 0,
  GeneralResponse_State_SUCCESS = 1,
  GeneralResponse_State_GeneralResponse_State_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GeneralResponse_State_GeneralResponse_State_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GeneralResponse_State_IsValid(int value);
const GeneralResponse_State GeneralResponse_State_State_MIN = GeneralResponse_State_FAILED;
const GeneralResponse_State GeneralResponse_State_State_MAX = GeneralResponse_State_SUCCESS;
const int GeneralResponse_State_State_ARRAYSIZE = GeneralResponse_State_State_MAX + 1;

const ::google::protobuf::EnumDescriptor* GeneralResponse_State_descriptor();
inline const ::std::string& GeneralResponse_State_Name(GeneralResponse_State value) {
  return ::google::protobuf::internal::NameOfEnum(
    GeneralResponse_State_descriptor(), value);
}
inline bool GeneralResponse_State_Parse(
    const ::std::string& name, GeneralResponse_State* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GeneralResponse_State>(
    GeneralResponse_State_descriptor(), name, value);
}
// ===================================================================

class GeneralResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:xsproto.communication.GeneralResponse) */ {
 public:
  GeneralResponse();
  virtual ~GeneralResponse();

  GeneralResponse(const GeneralResponse& from);

  inline GeneralResponse& operator=(const GeneralResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GeneralResponse(GeneralResponse&& from) noexcept
    : GeneralResponse() {
    *this = ::std::move(from);
  }

  inline GeneralResponse& operator=(GeneralResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GeneralResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GeneralResponse* internal_default_instance() {
    return reinterpret_cast<const GeneralResponse*>(
               &_GeneralResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GeneralResponse* other);
  friend void swap(GeneralResponse& a, GeneralResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GeneralResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  GeneralResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GeneralResponse& from);
  void MergeFrom(const GeneralResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GeneralResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GeneralResponse_State State;
  static const State FAILED =
    GeneralResponse_State_FAILED;
  static const State SUCCESS =
    GeneralResponse_State_SUCCESS;
  static inline bool State_IsValid(int value) {
    return GeneralResponse_State_IsValid(value);
  }
  static const State State_MIN =
    GeneralResponse_State_State_MIN;
  static const State State_MAX =
    GeneralResponse_State_State_MAX;
  static const int State_ARRAYSIZE =
    GeneralResponse_State_State_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  State_descriptor() {
    return GeneralResponse_State_descriptor();
  }
  static inline const ::std::string& State_Name(State value) {
    return GeneralResponse_State_Name(value);
  }
  static inline bool State_Parse(const ::std::string& name,
      State* value) {
    return GeneralResponse_State_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string error_msg = 6;
  void clear_error_msg();
  static const int kErrorMsgFieldNumber = 6;
  const ::std::string& error_msg() const;
  void set_error_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_error_msg(::std::string&& value);
  #endif
  void set_error_msg(const char* value);
  void set_error_msg(const char* value, size_t size);
  ::std::string* mutable_error_msg();
  ::std::string* release_error_msg();
  void set_allocated_error_msg(::std::string* error_msg);

  // .xsproto.base.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::xsproto::base::Header& header() const;
  ::xsproto::base::Header* release_header();
  ::xsproto::base::Header* mutable_header();
  void set_allocated_header(::xsproto::base::Header* header);

  // int64 timestamp = 2;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // int32 seq_num = 3;
  void clear_seq_num();
  static const int kSeqNumFieldNumber = 3;
  ::google::protobuf::int32 seq_num() const;
  void set_seq_num(::google::protobuf::int32 value);

  // .xsproto.communication.GeneralResponse.State state = 4;
  void clear_state();
  static const int kStateFieldNumber = 4;
  ::xsproto::communication::GeneralResponse_State state() const;
  void set_state(::xsproto::communication::GeneralResponse_State value);

  // int32 error_code = 5;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 5;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:xsproto.communication.GeneralResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr error_msg_;
  ::xsproto::base::Header* header_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::int32 seq_num_;
  int state_;
  ::google::protobuf::int32 error_code_;
  mutable int _cached_size_;
  friend struct ::protobuf_business_2fgeneral_5fresponse_2eproto::TableStruct;
  friend void ::protobuf_business_2fgeneral_5fresponse_2eproto::InitDefaultsGeneralResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GeneralResponse

// .xsproto.base.Header header = 1;
inline bool GeneralResponse::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::xsproto::base::Header& GeneralResponse::header() const {
  const ::xsproto::base::Header* p = header_;
  // @@protoc_insertion_point(field_get:xsproto.communication.GeneralResponse.header)
  return p != NULL ? *p : *reinterpret_cast<const ::xsproto::base::Header*>(
      &::xsproto::base::_Header_default_instance_);
}
inline ::xsproto::base::Header* GeneralResponse::release_header() {
  // @@protoc_insertion_point(field_release:xsproto.communication.GeneralResponse.header)
  
  ::xsproto::base::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::xsproto::base::Header* GeneralResponse::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::xsproto::base::Header;
  }
  // @@protoc_insertion_point(field_mutable:xsproto.communication.GeneralResponse.header)
  return header_;
}
inline void GeneralResponse::set_allocated_header(::xsproto::base::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:xsproto.communication.GeneralResponse.header)
}

// int64 timestamp = 2;
inline void GeneralResponse::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GeneralResponse::timestamp() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.GeneralResponse.timestamp)
  return timestamp_;
}
inline void GeneralResponse::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:xsproto.communication.GeneralResponse.timestamp)
}

// int32 seq_num = 3;
inline void GeneralResponse::clear_seq_num() {
  seq_num_ = 0;
}
inline ::google::protobuf::int32 GeneralResponse::seq_num() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.GeneralResponse.seq_num)
  return seq_num_;
}
inline void GeneralResponse::set_seq_num(::google::protobuf::int32 value) {
  
  seq_num_ = value;
  // @@protoc_insertion_point(field_set:xsproto.communication.GeneralResponse.seq_num)
}

// .xsproto.communication.GeneralResponse.State state = 4;
inline void GeneralResponse::clear_state() {
  state_ = 0;
}
inline ::xsproto::communication::GeneralResponse_State GeneralResponse::state() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.GeneralResponse.state)
  return static_cast< ::xsproto::communication::GeneralResponse_State >(state_);
}
inline void GeneralResponse::set_state(::xsproto::communication::GeneralResponse_State value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:xsproto.communication.GeneralResponse.state)
}

// int32 error_code = 5;
inline void GeneralResponse::clear_error_code() {
  error_code_ = 0;
}
inline ::google::protobuf::int32 GeneralResponse::error_code() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.GeneralResponse.error_code)
  return error_code_;
}
inline void GeneralResponse::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:xsproto.communication.GeneralResponse.error_code)
}

// string error_msg = 6;
inline void GeneralResponse::clear_error_msg() {
  error_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GeneralResponse::error_msg() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.GeneralResponse.error_msg)
  return error_msg_.GetNoArena();
}
inline void GeneralResponse::set_error_msg(const ::std::string& value) {
  
  error_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:xsproto.communication.GeneralResponse.error_msg)
}
#if LANG_CXX11
inline void GeneralResponse::set_error_msg(::std::string&& value) {
  
  error_msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xsproto.communication.GeneralResponse.error_msg)
}
#endif
inline void GeneralResponse::set_error_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xsproto.communication.GeneralResponse.error_msg)
}
inline void GeneralResponse::set_error_msg(const char* value, size_t size) {
  
  error_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xsproto.communication.GeneralResponse.error_msg)
}
inline ::std::string* GeneralResponse::mutable_error_msg() {
  
  // @@protoc_insertion_point(field_mutable:xsproto.communication.GeneralResponse.error_msg)
  return error_msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeneralResponse::release_error_msg() {
  // @@protoc_insertion_point(field_release:xsproto.communication.GeneralResponse.error_msg)
  
  return error_msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeneralResponse::set_allocated_error_msg(::std::string* error_msg) {
  if (error_msg != NULL) {
    
  } else {
    
  }
  error_msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_msg);
  // @@protoc_insertion_point(field_set_allocated:xsproto.communication.GeneralResponse.error_msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace communication
}  // namespace xsproto

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::xsproto::communication::GeneralResponse_State> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xsproto::communication::GeneralResponse_State>() {
  return ::xsproto::communication::GeneralResponse_State_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_business_2fgeneral_5fresponse_2eproto__INCLUDED
