// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: business/rubbish_detector_control_request.proto

#ifndef PROTOBUF_business_2frubbish_5fdetector_5fcontrol_5frequest_2eproto__INCLUDED
#define PROTOBUF_business_2frubbish_5fdetector_5fcontrol_5frequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "base/header.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_business_2frubbish_5fdetector_5fcontrol_5frequest_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsRubbishDetectorControlRequestImpl();
void InitDefaultsRubbishDetectorControlRequest();
inline void InitDefaults() {
  InitDefaultsRubbishDetectorControlRequest();
}
}  // namespace protobuf_business_2frubbish_5fdetector_5fcontrol_5frequest_2eproto
namespace xsproto {
namespace communication {
class RubbishDetectorControlRequest;
class RubbishDetectorControlRequestDefaultTypeInternal;
extern RubbishDetectorControlRequestDefaultTypeInternal _RubbishDetectorControlRequest_default_instance_;
}  // namespace communication
}  // namespace xsproto
namespace xsproto {
namespace communication {

enum SW_STATE {
  E_OPEN = 0,
  E_CLOSE = 1,
  SW_STATE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  SW_STATE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool SW_STATE_IsValid(int value);
const SW_STATE SW_STATE_MIN = E_OPEN;
const SW_STATE SW_STATE_MAX = E_CLOSE;
const int SW_STATE_ARRAYSIZE = SW_STATE_MAX + 1;

const ::google::protobuf::EnumDescriptor* SW_STATE_descriptor();
inline const ::std::string& SW_STATE_Name(SW_STATE value) {
  return ::google::protobuf::internal::NameOfEnum(
    SW_STATE_descriptor(), value);
}
inline bool SW_STATE_Parse(
    const ::std::string& name, SW_STATE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SW_STATE>(
    SW_STATE_descriptor(), name, value);
}
// ===================================================================

class RubbishDetectorControlRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:xsproto.communication.RubbishDetectorControlRequest) */ {
 public:
  RubbishDetectorControlRequest();
  virtual ~RubbishDetectorControlRequest();

  RubbishDetectorControlRequest(const RubbishDetectorControlRequest& from);

  inline RubbishDetectorControlRequest& operator=(const RubbishDetectorControlRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RubbishDetectorControlRequest(RubbishDetectorControlRequest&& from) noexcept
    : RubbishDetectorControlRequest() {
    *this = ::std::move(from);
  }

  inline RubbishDetectorControlRequest& operator=(RubbishDetectorControlRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RubbishDetectorControlRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RubbishDetectorControlRequest* internal_default_instance() {
    return reinterpret_cast<const RubbishDetectorControlRequest*>(
               &_RubbishDetectorControlRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RubbishDetectorControlRequest* other);
  friend void swap(RubbishDetectorControlRequest& a, RubbishDetectorControlRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RubbishDetectorControlRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  RubbishDetectorControlRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RubbishDetectorControlRequest& from);
  void MergeFrom(const RubbishDetectorControlRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RubbishDetectorControlRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .xsproto.base.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::xsproto::base::Header& header() const;
  ::xsproto::base::Header* release_header();
  ::xsproto::base::Header* mutable_header();
  void set_allocated_header(::xsproto::base::Header* header);

  // .xsproto.communication.SW_STATE sw_state = 2;
  void clear_sw_state();
  static const int kSwStateFieldNumber = 2;
  ::xsproto::communication::SW_STATE sw_state() const;
  void set_sw_state(::xsproto::communication::SW_STATE value);

  // int32 seq_num = 3;
  void clear_seq_num();
  static const int kSeqNumFieldNumber = 3;
  ::google::protobuf::int32 seq_num() const;
  void set_seq_num(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:xsproto.communication.RubbishDetectorControlRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::xsproto::base::Header* header_;
  int sw_state_;
  ::google::protobuf::int32 seq_num_;
  mutable int _cached_size_;
  friend struct ::protobuf_business_2frubbish_5fdetector_5fcontrol_5frequest_2eproto::TableStruct;
  friend void ::protobuf_business_2frubbish_5fdetector_5fcontrol_5frequest_2eproto::InitDefaultsRubbishDetectorControlRequestImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RubbishDetectorControlRequest

// .xsproto.base.Header header = 1;
inline bool RubbishDetectorControlRequest::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::xsproto::base::Header& RubbishDetectorControlRequest::header() const {
  const ::xsproto::base::Header* p = header_;
  // @@protoc_insertion_point(field_get:xsproto.communication.RubbishDetectorControlRequest.header)
  return p != NULL ? *p : *reinterpret_cast<const ::xsproto::base::Header*>(
      &::xsproto::base::_Header_default_instance_);
}
inline ::xsproto::base::Header* RubbishDetectorControlRequest::release_header() {
  // @@protoc_insertion_point(field_release:xsproto.communication.RubbishDetectorControlRequest.header)
  
  ::xsproto::base::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::xsproto::base::Header* RubbishDetectorControlRequest::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::xsproto::base::Header;
  }
  // @@protoc_insertion_point(field_mutable:xsproto.communication.RubbishDetectorControlRequest.header)
  return header_;
}
inline void RubbishDetectorControlRequest::set_allocated_header(::xsproto::base::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:xsproto.communication.RubbishDetectorControlRequest.header)
}

// .xsproto.communication.SW_STATE sw_state = 2;
inline void RubbishDetectorControlRequest::clear_sw_state() {
  sw_state_ = 0;
}
inline ::xsproto::communication::SW_STATE RubbishDetectorControlRequest::sw_state() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.RubbishDetectorControlRequest.sw_state)
  return static_cast< ::xsproto::communication::SW_STATE >(sw_state_);
}
inline void RubbishDetectorControlRequest::set_sw_state(::xsproto::communication::SW_STATE value) {
  
  sw_state_ = value;
  // @@protoc_insertion_point(field_set:xsproto.communication.RubbishDetectorControlRequest.sw_state)
}

// int32 seq_num = 3;
inline void RubbishDetectorControlRequest::clear_seq_num() {
  seq_num_ = 0;
}
inline ::google::protobuf::int32 RubbishDetectorControlRequest::seq_num() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.RubbishDetectorControlRequest.seq_num)
  return seq_num_;
}
inline void RubbishDetectorControlRequest::set_seq_num(::google::protobuf::int32 value) {
  
  seq_num_ = value;
  // @@protoc_insertion_point(field_set:xsproto.communication.RubbishDetectorControlRequest.seq_num)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace communication
}  // namespace xsproto

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::xsproto::communication::SW_STATE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xsproto::communication::SW_STATE>() {
  return ::xsproto::communication::SW_STATE_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_business_2frubbish_5fdetector_5fcontrol_5frequest_2eproto__INCLUDED
