// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: perception/sync_radar_camera_fusion_data.proto

#ifndef PROTOBUF_perception_2fsync_5fradar_5fcamera_5ffusion_5fdata_2eproto__INCLUDED
#define PROTOBUF_perception_2fsync_5fradar_5fcamera_5ffusion_5fdata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "base/header.pb.h"
#include "perception/perception_common.pb.h"
#include "perception/radar_data.pb.h"
#include "perception/mono_camera_data.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_perception_2fsync_5fradar_5fcamera_5ffusion_5fdata_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSyncRadarCameraFusionDataImpl();
void InitDefaultsSyncRadarCameraFusionData();
inline void InitDefaults() {
  InitDefaultsSyncRadarCameraFusionData();
}
}  // namespace protobuf_perception_2fsync_5fradar_5fcamera_5ffusion_5fdata_2eproto
namespace xsproto {
namespace perception {
class SyncRadarCameraFusionData;
class SyncRadarCameraFusionDataDefaultTypeInternal;
extern SyncRadarCameraFusionDataDefaultTypeInternal _SyncRadarCameraFusionData_default_instance_;
}  // namespace perception
}  // namespace xsproto
namespace xsproto {
namespace perception {

// ===================================================================

class SyncRadarCameraFusionData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:xsproto.perception.SyncRadarCameraFusionData) */ {
 public:
  SyncRadarCameraFusionData();
  virtual ~SyncRadarCameraFusionData();

  SyncRadarCameraFusionData(const SyncRadarCameraFusionData& from);

  inline SyncRadarCameraFusionData& operator=(const SyncRadarCameraFusionData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SyncRadarCameraFusionData(SyncRadarCameraFusionData&& from) noexcept
    : SyncRadarCameraFusionData() {
    *this = ::std::move(from);
  }

  inline SyncRadarCameraFusionData& operator=(SyncRadarCameraFusionData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SyncRadarCameraFusionData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SyncRadarCameraFusionData* internal_default_instance() {
    return reinterpret_cast<const SyncRadarCameraFusionData*>(
               &_SyncRadarCameraFusionData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SyncRadarCameraFusionData* other);
  friend void swap(SyncRadarCameraFusionData& a, SyncRadarCameraFusionData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SyncRadarCameraFusionData* New() const PROTOBUF_FINAL { return New(NULL); }

  SyncRadarCameraFusionData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SyncRadarCameraFusionData& from);
  void MergeFrom(const SyncRadarCameraFusionData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SyncRadarCameraFusionData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .xsproto.perception.RadarPoint radar_points = 13;
  int radar_points_size() const;
  void clear_radar_points();
  static const int kRadarPointsFieldNumber = 13;
  const ::xsproto::perception::RadarPoint& radar_points(int index) const;
  ::xsproto::perception::RadarPoint* mutable_radar_points(int index);
  ::xsproto::perception::RadarPoint* add_radar_points();
  ::google::protobuf::RepeatedPtrField< ::xsproto::perception::RadarPoint >*
      mutable_radar_points();
  const ::google::protobuf::RepeatedPtrField< ::xsproto::perception::RadarPoint >&
      radar_points() const;

  // repeated .xsproto.perception.RadarObject radar_objects = 14;
  int radar_objects_size() const;
  void clear_radar_objects();
  static const int kRadarObjectsFieldNumber = 14;
  const ::xsproto::perception::RadarObject& radar_objects(int index) const;
  ::xsproto::perception::RadarObject* mutable_radar_objects(int index);
  ::xsproto::perception::RadarObject* add_radar_objects();
  ::google::protobuf::RepeatedPtrField< ::xsproto::perception::RadarObject >*
      mutable_radar_objects();
  const ::google::protobuf::RepeatedPtrField< ::xsproto::perception::RadarObject >&
      radar_objects() const;

  // bytes image_data = 8;
  void clear_image_data();
  static const int kImageDataFieldNumber = 8;
  const ::std::string& image_data() const;
  void set_image_data(const ::std::string& value);
  #if LANG_CXX11
  void set_image_data(::std::string&& value);
  #endif
  void set_image_data(const char* value);
  void set_image_data(const void* value, size_t size);
  ::std::string* mutable_image_data();
  ::std::string* release_image_data();
  void set_allocated_image_data(::std::string* image_data);

  // .xsproto.base.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::xsproto::base::Header& header() const;
  ::xsproto::base::Header* release_header();
  ::xsproto::base::Header* mutable_header();
  void set_allocated_header(::xsproto::base::Header* header);

  // .xsproto.perception.CamearaIntrinsicParameters intrinsic_params = 10;
  bool has_intrinsic_params() const;
  void clear_intrinsic_params();
  static const int kIntrinsicParamsFieldNumber = 10;
  const ::xsproto::perception::CamearaIntrinsicParameters& intrinsic_params() const;
  ::xsproto::perception::CamearaIntrinsicParameters* release_intrinsic_params();
  ::xsproto::perception::CamearaIntrinsicParameters* mutable_intrinsic_params();
  void set_allocated_intrinsic_params(::xsproto::perception::CamearaIntrinsicParameters* intrinsic_params);

  // .xsproto.perception.ExtrinsicParameters camera_extrinsic_params = 11;
  bool has_camera_extrinsic_params() const;
  void clear_camera_extrinsic_params();
  static const int kCameraExtrinsicParamsFieldNumber = 11;
  const ::xsproto::perception::ExtrinsicParameters& camera_extrinsic_params() const;
  ::xsproto::perception::ExtrinsicParameters* release_camera_extrinsic_params();
  ::xsproto::perception::ExtrinsicParameters* mutable_camera_extrinsic_params();
  void set_allocated_camera_extrinsic_params(::xsproto::perception::ExtrinsicParameters* camera_extrinsic_params);

  // .xsproto.perception.ExtrinsicParameters radar_extrinsic_params = 12;
  bool has_radar_extrinsic_params() const;
  void clear_radar_extrinsic_params();
  static const int kRadarExtrinsicParamsFieldNumber = 12;
  const ::xsproto::perception::ExtrinsicParameters& radar_extrinsic_params() const;
  ::xsproto::perception::ExtrinsicParameters* release_radar_extrinsic_params();
  ::xsproto::perception::ExtrinsicParameters* mutable_radar_extrinsic_params();
  void set_allocated_radar_extrinsic_params(::xsproto::perception::ExtrinsicParameters* radar_extrinsic_params);

  // uint32 camera_type = 2;
  void clear_camera_type();
  static const int kCameraTypeFieldNumber = 2;
  ::google::protobuf::uint32 camera_type() const;
  void set_camera_type(::google::protobuf::uint32 value);

  // uint32 camera_mode = 3;
  void clear_camera_mode();
  static const int kCameraModeFieldNumber = 3;
  ::google::protobuf::uint32 camera_mode() const;
  void set_camera_mode(::google::protobuf::uint32 value);

  // uint32 width = 4;
  void clear_width();
  static const int kWidthFieldNumber = 4;
  ::google::protobuf::uint32 width() const;
  void set_width(::google::protobuf::uint32 value);

  // uint32 height = 5;
  void clear_height();
  static const int kHeightFieldNumber = 5;
  ::google::protobuf::uint32 height() const;
  void set_height(::google::protobuf::uint32 value);

  // uint32 pixel_channel = 6;
  void clear_pixel_channel();
  static const int kPixelChannelFieldNumber = 6;
  ::google::protobuf::uint32 pixel_channel() const;
  void set_pixel_channel(::google::protobuf::uint32 value);

  // uint32 image_format = 7;
  void clear_image_format();
  static const int kImageFormatFieldNumber = 7;
  ::google::protobuf::uint32 image_format() const;
  void set_image_format(::google::protobuf::uint32 value);

  // .xsproto.perception.LenMode len_mode = 9;
  void clear_len_mode();
  static const int kLenModeFieldNumber = 9;
  ::xsproto::perception::LenMode len_mode() const;
  void set_len_mode(::xsproto::perception::LenMode value);

  // @@protoc_insertion_point(class_scope:xsproto.perception.SyncRadarCameraFusionData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::xsproto::perception::RadarPoint > radar_points_;
  ::google::protobuf::RepeatedPtrField< ::xsproto::perception::RadarObject > radar_objects_;
  ::google::protobuf::internal::ArenaStringPtr image_data_;
  ::xsproto::base::Header* header_;
  ::xsproto::perception::CamearaIntrinsicParameters* intrinsic_params_;
  ::xsproto::perception::ExtrinsicParameters* camera_extrinsic_params_;
  ::xsproto::perception::ExtrinsicParameters* radar_extrinsic_params_;
  ::google::protobuf::uint32 camera_type_;
  ::google::protobuf::uint32 camera_mode_;
  ::google::protobuf::uint32 width_;
  ::google::protobuf::uint32 height_;
  ::google::protobuf::uint32 pixel_channel_;
  ::google::protobuf::uint32 image_format_;
  int len_mode_;
  mutable int _cached_size_;
  friend struct ::protobuf_perception_2fsync_5fradar_5fcamera_5ffusion_5fdata_2eproto::TableStruct;
  friend void ::protobuf_perception_2fsync_5fradar_5fcamera_5ffusion_5fdata_2eproto::InitDefaultsSyncRadarCameraFusionDataImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SyncRadarCameraFusionData

// .xsproto.base.Header header = 1;
inline bool SyncRadarCameraFusionData::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::xsproto::base::Header& SyncRadarCameraFusionData::header() const {
  const ::xsproto::base::Header* p = header_;
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.header)
  return p != NULL ? *p : *reinterpret_cast<const ::xsproto::base::Header*>(
      &::xsproto::base::_Header_default_instance_);
}
inline ::xsproto::base::Header* SyncRadarCameraFusionData::release_header() {
  // @@protoc_insertion_point(field_release:xsproto.perception.SyncRadarCameraFusionData.header)
  
  ::xsproto::base::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::xsproto::base::Header* SyncRadarCameraFusionData::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::xsproto::base::Header;
  }
  // @@protoc_insertion_point(field_mutable:xsproto.perception.SyncRadarCameraFusionData.header)
  return header_;
}
inline void SyncRadarCameraFusionData::set_allocated_header(::xsproto::base::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:xsproto.perception.SyncRadarCameraFusionData.header)
}

// uint32 camera_type = 2;
inline void SyncRadarCameraFusionData::clear_camera_type() {
  camera_type_ = 0u;
}
inline ::google::protobuf::uint32 SyncRadarCameraFusionData::camera_type() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.camera_type)
  return camera_type_;
}
inline void SyncRadarCameraFusionData::set_camera_type(::google::protobuf::uint32 value) {
  
  camera_type_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncRadarCameraFusionData.camera_type)
}

// uint32 camera_mode = 3;
inline void SyncRadarCameraFusionData::clear_camera_mode() {
  camera_mode_ = 0u;
}
inline ::google::protobuf::uint32 SyncRadarCameraFusionData::camera_mode() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.camera_mode)
  return camera_mode_;
}
inline void SyncRadarCameraFusionData::set_camera_mode(::google::protobuf::uint32 value) {
  
  camera_mode_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncRadarCameraFusionData.camera_mode)
}

// uint32 width = 4;
inline void SyncRadarCameraFusionData::clear_width() {
  width_ = 0u;
}
inline ::google::protobuf::uint32 SyncRadarCameraFusionData::width() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.width)
  return width_;
}
inline void SyncRadarCameraFusionData::set_width(::google::protobuf::uint32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncRadarCameraFusionData.width)
}

// uint32 height = 5;
inline void SyncRadarCameraFusionData::clear_height() {
  height_ = 0u;
}
inline ::google::protobuf::uint32 SyncRadarCameraFusionData::height() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.height)
  return height_;
}
inline void SyncRadarCameraFusionData::set_height(::google::protobuf::uint32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncRadarCameraFusionData.height)
}

// uint32 pixel_channel = 6;
inline void SyncRadarCameraFusionData::clear_pixel_channel() {
  pixel_channel_ = 0u;
}
inline ::google::protobuf::uint32 SyncRadarCameraFusionData::pixel_channel() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.pixel_channel)
  return pixel_channel_;
}
inline void SyncRadarCameraFusionData::set_pixel_channel(::google::protobuf::uint32 value) {
  
  pixel_channel_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncRadarCameraFusionData.pixel_channel)
}

// uint32 image_format = 7;
inline void SyncRadarCameraFusionData::clear_image_format() {
  image_format_ = 0u;
}
inline ::google::protobuf::uint32 SyncRadarCameraFusionData::image_format() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.image_format)
  return image_format_;
}
inline void SyncRadarCameraFusionData::set_image_format(::google::protobuf::uint32 value) {
  
  image_format_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncRadarCameraFusionData.image_format)
}

// bytes image_data = 8;
inline void SyncRadarCameraFusionData::clear_image_data() {
  image_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SyncRadarCameraFusionData::image_data() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.image_data)
  return image_data_.GetNoArena();
}
inline void SyncRadarCameraFusionData::set_image_data(const ::std::string& value) {
  
  image_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncRadarCameraFusionData.image_data)
}
#if LANG_CXX11
inline void SyncRadarCameraFusionData::set_image_data(::std::string&& value) {
  
  image_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xsproto.perception.SyncRadarCameraFusionData.image_data)
}
#endif
inline void SyncRadarCameraFusionData::set_image_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  image_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xsproto.perception.SyncRadarCameraFusionData.image_data)
}
inline void SyncRadarCameraFusionData::set_image_data(const void* value, size_t size) {
  
  image_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xsproto.perception.SyncRadarCameraFusionData.image_data)
}
inline ::std::string* SyncRadarCameraFusionData::mutable_image_data() {
  
  // @@protoc_insertion_point(field_mutable:xsproto.perception.SyncRadarCameraFusionData.image_data)
  return image_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SyncRadarCameraFusionData::release_image_data() {
  // @@protoc_insertion_point(field_release:xsproto.perception.SyncRadarCameraFusionData.image_data)
  
  return image_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SyncRadarCameraFusionData::set_allocated_image_data(::std::string* image_data) {
  if (image_data != NULL) {
    
  } else {
    
  }
  image_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), image_data);
  // @@protoc_insertion_point(field_set_allocated:xsproto.perception.SyncRadarCameraFusionData.image_data)
}

// .xsproto.perception.LenMode len_mode = 9;
inline void SyncRadarCameraFusionData::clear_len_mode() {
  len_mode_ = 0;
}
inline ::xsproto::perception::LenMode SyncRadarCameraFusionData::len_mode() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.len_mode)
  return static_cast< ::xsproto::perception::LenMode >(len_mode_);
}
inline void SyncRadarCameraFusionData::set_len_mode(::xsproto::perception::LenMode value) {
  
  len_mode_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncRadarCameraFusionData.len_mode)
}

// .xsproto.perception.CamearaIntrinsicParameters intrinsic_params = 10;
inline bool SyncRadarCameraFusionData::has_intrinsic_params() const {
  return this != internal_default_instance() && intrinsic_params_ != NULL;
}
inline const ::xsproto::perception::CamearaIntrinsicParameters& SyncRadarCameraFusionData::intrinsic_params() const {
  const ::xsproto::perception::CamearaIntrinsicParameters* p = intrinsic_params_;
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.intrinsic_params)
  return p != NULL ? *p : *reinterpret_cast<const ::xsproto::perception::CamearaIntrinsicParameters*>(
      &::xsproto::perception::_CamearaIntrinsicParameters_default_instance_);
}
inline ::xsproto::perception::CamearaIntrinsicParameters* SyncRadarCameraFusionData::release_intrinsic_params() {
  // @@protoc_insertion_point(field_release:xsproto.perception.SyncRadarCameraFusionData.intrinsic_params)
  
  ::xsproto::perception::CamearaIntrinsicParameters* temp = intrinsic_params_;
  intrinsic_params_ = NULL;
  return temp;
}
inline ::xsproto::perception::CamearaIntrinsicParameters* SyncRadarCameraFusionData::mutable_intrinsic_params() {
  
  if (intrinsic_params_ == NULL) {
    intrinsic_params_ = new ::xsproto::perception::CamearaIntrinsicParameters;
  }
  // @@protoc_insertion_point(field_mutable:xsproto.perception.SyncRadarCameraFusionData.intrinsic_params)
  return intrinsic_params_;
}
inline void SyncRadarCameraFusionData::set_allocated_intrinsic_params(::xsproto::perception::CamearaIntrinsicParameters* intrinsic_params) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(intrinsic_params_);
  }
  if (intrinsic_params) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      intrinsic_params = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, intrinsic_params, submessage_arena);
    }
    
  } else {
    
  }
  intrinsic_params_ = intrinsic_params;
  // @@protoc_insertion_point(field_set_allocated:xsproto.perception.SyncRadarCameraFusionData.intrinsic_params)
}

// .xsproto.perception.ExtrinsicParameters camera_extrinsic_params = 11;
inline bool SyncRadarCameraFusionData::has_camera_extrinsic_params() const {
  return this != internal_default_instance() && camera_extrinsic_params_ != NULL;
}
inline const ::xsproto::perception::ExtrinsicParameters& SyncRadarCameraFusionData::camera_extrinsic_params() const {
  const ::xsproto::perception::ExtrinsicParameters* p = camera_extrinsic_params_;
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.camera_extrinsic_params)
  return p != NULL ? *p : *reinterpret_cast<const ::xsproto::perception::ExtrinsicParameters*>(
      &::xsproto::perception::_ExtrinsicParameters_default_instance_);
}
inline ::xsproto::perception::ExtrinsicParameters* SyncRadarCameraFusionData::release_camera_extrinsic_params() {
  // @@protoc_insertion_point(field_release:xsproto.perception.SyncRadarCameraFusionData.camera_extrinsic_params)
  
  ::xsproto::perception::ExtrinsicParameters* temp = camera_extrinsic_params_;
  camera_extrinsic_params_ = NULL;
  return temp;
}
inline ::xsproto::perception::ExtrinsicParameters* SyncRadarCameraFusionData::mutable_camera_extrinsic_params() {
  
  if (camera_extrinsic_params_ == NULL) {
    camera_extrinsic_params_ = new ::xsproto::perception::ExtrinsicParameters;
  }
  // @@protoc_insertion_point(field_mutable:xsproto.perception.SyncRadarCameraFusionData.camera_extrinsic_params)
  return camera_extrinsic_params_;
}
inline void SyncRadarCameraFusionData::set_allocated_camera_extrinsic_params(::xsproto::perception::ExtrinsicParameters* camera_extrinsic_params) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(camera_extrinsic_params_);
  }
  if (camera_extrinsic_params) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      camera_extrinsic_params = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, camera_extrinsic_params, submessage_arena);
    }
    
  } else {
    
  }
  camera_extrinsic_params_ = camera_extrinsic_params;
  // @@protoc_insertion_point(field_set_allocated:xsproto.perception.SyncRadarCameraFusionData.camera_extrinsic_params)
}

// .xsproto.perception.ExtrinsicParameters radar_extrinsic_params = 12;
inline bool SyncRadarCameraFusionData::has_radar_extrinsic_params() const {
  return this != internal_default_instance() && radar_extrinsic_params_ != NULL;
}
inline const ::xsproto::perception::ExtrinsicParameters& SyncRadarCameraFusionData::radar_extrinsic_params() const {
  const ::xsproto::perception::ExtrinsicParameters* p = radar_extrinsic_params_;
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.radar_extrinsic_params)
  return p != NULL ? *p : *reinterpret_cast<const ::xsproto::perception::ExtrinsicParameters*>(
      &::xsproto::perception::_ExtrinsicParameters_default_instance_);
}
inline ::xsproto::perception::ExtrinsicParameters* SyncRadarCameraFusionData::release_radar_extrinsic_params() {
  // @@protoc_insertion_point(field_release:xsproto.perception.SyncRadarCameraFusionData.radar_extrinsic_params)
  
  ::xsproto::perception::ExtrinsicParameters* temp = radar_extrinsic_params_;
  radar_extrinsic_params_ = NULL;
  return temp;
}
inline ::xsproto::perception::ExtrinsicParameters* SyncRadarCameraFusionData::mutable_radar_extrinsic_params() {
  
  if (radar_extrinsic_params_ == NULL) {
    radar_extrinsic_params_ = new ::xsproto::perception::ExtrinsicParameters;
  }
  // @@protoc_insertion_point(field_mutable:xsproto.perception.SyncRadarCameraFusionData.radar_extrinsic_params)
  return radar_extrinsic_params_;
}
inline void SyncRadarCameraFusionData::set_allocated_radar_extrinsic_params(::xsproto::perception::ExtrinsicParameters* radar_extrinsic_params) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(radar_extrinsic_params_);
  }
  if (radar_extrinsic_params) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      radar_extrinsic_params = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, radar_extrinsic_params, submessage_arena);
    }
    
  } else {
    
  }
  radar_extrinsic_params_ = radar_extrinsic_params;
  // @@protoc_insertion_point(field_set_allocated:xsproto.perception.SyncRadarCameraFusionData.radar_extrinsic_params)
}

// repeated .xsproto.perception.RadarPoint radar_points = 13;
inline int SyncRadarCameraFusionData::radar_points_size() const {
  return radar_points_.size();
}
inline const ::xsproto::perception::RadarPoint& SyncRadarCameraFusionData::radar_points(int index) const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.radar_points)
  return radar_points_.Get(index);
}
inline ::xsproto::perception::RadarPoint* SyncRadarCameraFusionData::mutable_radar_points(int index) {
  // @@protoc_insertion_point(field_mutable:xsproto.perception.SyncRadarCameraFusionData.radar_points)
  return radar_points_.Mutable(index);
}
inline ::xsproto::perception::RadarPoint* SyncRadarCameraFusionData::add_radar_points() {
  // @@protoc_insertion_point(field_add:xsproto.perception.SyncRadarCameraFusionData.radar_points)
  return radar_points_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::xsproto::perception::RadarPoint >*
SyncRadarCameraFusionData::mutable_radar_points() {
  // @@protoc_insertion_point(field_mutable_list:xsproto.perception.SyncRadarCameraFusionData.radar_points)
  return &radar_points_;
}
inline const ::google::protobuf::RepeatedPtrField< ::xsproto::perception::RadarPoint >&
SyncRadarCameraFusionData::radar_points() const {
  // @@protoc_insertion_point(field_list:xsproto.perception.SyncRadarCameraFusionData.radar_points)
  return radar_points_;
}

// repeated .xsproto.perception.RadarObject radar_objects = 14;
inline int SyncRadarCameraFusionData::radar_objects_size() const {
  return radar_objects_.size();
}
inline const ::xsproto::perception::RadarObject& SyncRadarCameraFusionData::radar_objects(int index) const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncRadarCameraFusionData.radar_objects)
  return radar_objects_.Get(index);
}
inline ::xsproto::perception::RadarObject* SyncRadarCameraFusionData::mutable_radar_objects(int index) {
  // @@protoc_insertion_point(field_mutable:xsproto.perception.SyncRadarCameraFusionData.radar_objects)
  return radar_objects_.Mutable(index);
}
inline ::xsproto::perception::RadarObject* SyncRadarCameraFusionData::add_radar_objects() {
  // @@protoc_insertion_point(field_add:xsproto.perception.SyncRadarCameraFusionData.radar_objects)
  return radar_objects_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::xsproto::perception::RadarObject >*
SyncRadarCameraFusionData::mutable_radar_objects() {
  // @@protoc_insertion_point(field_mutable_list:xsproto.perception.SyncRadarCameraFusionData.radar_objects)
  return &radar_objects_;
}
inline const ::google::protobuf::RepeatedPtrField< ::xsproto::perception::RadarObject >&
SyncRadarCameraFusionData::radar_objects() const {
  // @@protoc_insertion_point(field_list:xsproto.perception.SyncRadarCameraFusionData.radar_objects)
  return radar_objects_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace perception
}  // namespace xsproto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_perception_2fsync_5fradar_5fcamera_5ffusion_5fdata_2eproto__INCLUDED
