// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: business/nec_control_response.proto

#ifndef PROTOBUF_business_2fnec_5fcontrol_5fresponse_2eproto__INCLUDED
#define PROTOBUF_business_2fnec_5fcontrol_5fresponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "base/header.pb.h"
#include "business/nec_control_request.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_business_2fnec_5fcontrol_5fresponse_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsNecControlResponseImpl();
void InitDefaultsNecControlResponse();
inline void InitDefaults() {
  InitDefaultsNecControlResponse();
}
}  // namespace protobuf_business_2fnec_5fcontrol_5fresponse_2eproto
namespace xsproto {
namespace communication {
class NecControlResponse;
class NecControlResponseDefaultTypeInternal;
extern NecControlResponseDefaultTypeInternal _NecControlResponse_default_instance_;
}  // namespace communication
}  // namespace xsproto
namespace xsproto {
namespace communication {

// ===================================================================

class NecControlResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:xsproto.communication.NecControlResponse) */ {
 public:
  NecControlResponse();
  virtual ~NecControlResponse();

  NecControlResponse(const NecControlResponse& from);

  inline NecControlResponse& operator=(const NecControlResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NecControlResponse(NecControlResponse&& from) noexcept
    : NecControlResponse() {
    *this = ::std::move(from);
  }

  inline NecControlResponse& operator=(NecControlResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NecControlResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NecControlResponse* internal_default_instance() {
    return reinterpret_cast<const NecControlResponse*>(
               &_NecControlResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(NecControlResponse* other);
  friend void swap(NecControlResponse& a, NecControlResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NecControlResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  NecControlResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NecControlResponse& from);
  void MergeFrom(const NecControlResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NecControlResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .xsproto.communication.NecDeviceInfo nec_device_infos = 6;
  int nec_device_infos_size() const;
  void clear_nec_device_infos();
  static const int kNecDeviceInfosFieldNumber = 6;
  const ::xsproto::communication::NecDeviceInfo& nec_device_infos(int index) const;
  ::xsproto::communication::NecDeviceInfo* mutable_nec_device_infos(int index);
  ::xsproto::communication::NecDeviceInfo* add_nec_device_infos();
  ::google::protobuf::RepeatedPtrField< ::xsproto::communication::NecDeviceInfo >*
      mutable_nec_device_infos();
  const ::google::protobuf::RepeatedPtrField< ::xsproto::communication::NecDeviceInfo >&
      nec_device_infos() const;

  // string error_msg = 5;
  void clear_error_msg();
  static const int kErrorMsgFieldNumber = 5;
  const ::std::string& error_msg() const;
  void set_error_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_error_msg(::std::string&& value);
  #endif
  void set_error_msg(const char* value);
  void set_error_msg(const char* value, size_t size);
  ::std::string* mutable_error_msg();
  ::std::string* release_error_msg();
  void set_allocated_error_msg(::std::string* error_msg);

  // .xsproto.base.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::xsproto::base::Header& header() const;
  ::xsproto::base::Header* release_header();
  ::xsproto::base::Header* mutable_header();
  void set_allocated_header(::xsproto::base::Header* header);

  // int64 timestamp = 2;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // int32 seq_num = 3;
  void clear_seq_num();
  static const int kSeqNumFieldNumber = 3;
  ::google::protobuf::int32 seq_num() const;
  void set_seq_num(::google::protobuf::int32 value);

  // int32 result = 4;
  void clear_result();
  static const int kResultFieldNumber = 4;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:xsproto.communication.NecControlResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::xsproto::communication::NecDeviceInfo > nec_device_infos_;
  ::google::protobuf::internal::ArenaStringPtr error_msg_;
  ::xsproto::base::Header* header_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::int32 seq_num_;
  ::google::protobuf::int32 result_;
  mutable int _cached_size_;
  friend struct ::protobuf_business_2fnec_5fcontrol_5fresponse_2eproto::TableStruct;
  friend void ::protobuf_business_2fnec_5fcontrol_5fresponse_2eproto::InitDefaultsNecControlResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NecControlResponse

// .xsproto.base.Header header = 1;
inline bool NecControlResponse::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::xsproto::base::Header& NecControlResponse::header() const {
  const ::xsproto::base::Header* p = header_;
  // @@protoc_insertion_point(field_get:xsproto.communication.NecControlResponse.header)
  return p != NULL ? *p : *reinterpret_cast<const ::xsproto::base::Header*>(
      &::xsproto::base::_Header_default_instance_);
}
inline ::xsproto::base::Header* NecControlResponse::release_header() {
  // @@protoc_insertion_point(field_release:xsproto.communication.NecControlResponse.header)
  
  ::xsproto::base::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::xsproto::base::Header* NecControlResponse::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::xsproto::base::Header;
  }
  // @@protoc_insertion_point(field_mutable:xsproto.communication.NecControlResponse.header)
  return header_;
}
inline void NecControlResponse::set_allocated_header(::xsproto::base::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:xsproto.communication.NecControlResponse.header)
}

// int64 timestamp = 2;
inline void NecControlResponse::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 NecControlResponse::timestamp() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.NecControlResponse.timestamp)
  return timestamp_;
}
inline void NecControlResponse::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:xsproto.communication.NecControlResponse.timestamp)
}

// int32 seq_num = 3;
inline void NecControlResponse::clear_seq_num() {
  seq_num_ = 0;
}
inline ::google::protobuf::int32 NecControlResponse::seq_num() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.NecControlResponse.seq_num)
  return seq_num_;
}
inline void NecControlResponse::set_seq_num(::google::protobuf::int32 value) {
  
  seq_num_ = value;
  // @@protoc_insertion_point(field_set:xsproto.communication.NecControlResponse.seq_num)
}

// int32 result = 4;
inline void NecControlResponse::clear_result() {
  result_ = 0;
}
inline ::google::protobuf::int32 NecControlResponse::result() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.NecControlResponse.result)
  return result_;
}
inline void NecControlResponse::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:xsproto.communication.NecControlResponse.result)
}

// string error_msg = 5;
inline void NecControlResponse::clear_error_msg() {
  error_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NecControlResponse::error_msg() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.NecControlResponse.error_msg)
  return error_msg_.GetNoArena();
}
inline void NecControlResponse::set_error_msg(const ::std::string& value) {
  
  error_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:xsproto.communication.NecControlResponse.error_msg)
}
#if LANG_CXX11
inline void NecControlResponse::set_error_msg(::std::string&& value) {
  
  error_msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xsproto.communication.NecControlResponse.error_msg)
}
#endif
inline void NecControlResponse::set_error_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xsproto.communication.NecControlResponse.error_msg)
}
inline void NecControlResponse::set_error_msg(const char* value, size_t size) {
  
  error_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xsproto.communication.NecControlResponse.error_msg)
}
inline ::std::string* NecControlResponse::mutable_error_msg() {
  
  // @@protoc_insertion_point(field_mutable:xsproto.communication.NecControlResponse.error_msg)
  return error_msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NecControlResponse::release_error_msg() {
  // @@protoc_insertion_point(field_release:xsproto.communication.NecControlResponse.error_msg)
  
  return error_msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NecControlResponse::set_allocated_error_msg(::std::string* error_msg) {
  if (error_msg != NULL) {
    
  } else {
    
  }
  error_msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_msg);
  // @@protoc_insertion_point(field_set_allocated:xsproto.communication.NecControlResponse.error_msg)
}

// repeated .xsproto.communication.NecDeviceInfo nec_device_infos = 6;
inline int NecControlResponse::nec_device_infos_size() const {
  return nec_device_infos_.size();
}
inline const ::xsproto::communication::NecDeviceInfo& NecControlResponse::nec_device_infos(int index) const {
  // @@protoc_insertion_point(field_get:xsproto.communication.NecControlResponse.nec_device_infos)
  return nec_device_infos_.Get(index);
}
inline ::xsproto::communication::NecDeviceInfo* NecControlResponse::mutable_nec_device_infos(int index) {
  // @@protoc_insertion_point(field_mutable:xsproto.communication.NecControlResponse.nec_device_infos)
  return nec_device_infos_.Mutable(index);
}
inline ::xsproto::communication::NecDeviceInfo* NecControlResponse::add_nec_device_infos() {
  // @@protoc_insertion_point(field_add:xsproto.communication.NecControlResponse.nec_device_infos)
  return nec_device_infos_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::xsproto::communication::NecDeviceInfo >*
NecControlResponse::mutable_nec_device_infos() {
  // @@protoc_insertion_point(field_mutable_list:xsproto.communication.NecControlResponse.nec_device_infos)
  return &nec_device_infos_;
}
inline const ::google::protobuf::RepeatedPtrField< ::xsproto::communication::NecDeviceInfo >&
NecControlResponse::nec_device_infos() const {
  // @@protoc_insertion_point(field_list:xsproto.communication.NecControlResponse.nec_device_infos)
  return nec_device_infos_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace communication
}  // namespace xsproto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_business_2fnec_5fcontrol_5fresponse_2eproto__INCLUDED
