// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: business/path_net_info.proto

#ifndef PROTOBUF_business_2fpath_5fnet_5finfo_2eproto__INCLUDED
#define PROTOBUF_business_2fpath_5fnet_5finfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_business_2fpath_5fnet_5finfo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsPathNetInfoImpl();
void InitDefaultsPathNetInfo();
inline void InitDefaults() {
  InitDefaultsPathNetInfo();
}
}  // namespace protobuf_business_2fpath_5fnet_5finfo_2eproto
namespace xsproto {
namespace communication {
class PathNetInfo;
class PathNetInfoDefaultTypeInternal;
extern PathNetInfoDefaultTypeInternal _PathNetInfo_default_instance_;
}  // namespace communication
}  // namespace xsproto
namespace xsproto {
namespace communication {

// ===================================================================

class PathNetInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:xsproto.communication.PathNetInfo) */ {
 public:
  PathNetInfo();
  virtual ~PathNetInfo();

  PathNetInfo(const PathNetInfo& from);

  inline PathNetInfo& operator=(const PathNetInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PathNetInfo(PathNetInfo&& from) noexcept
    : PathNetInfo() {
    *this = ::std::move(from);
  }

  inline PathNetInfo& operator=(PathNetInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PathNetInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PathNetInfo* internal_default_instance() {
    return reinterpret_cast<const PathNetInfo*>(
               &_PathNetInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PathNetInfo* other);
  friend void swap(PathNetInfo& a, PathNetInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PathNetInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  PathNetInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PathNetInfo& from);
  void MergeFrom(const PathNetInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PathNetInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string pcd_path = 1;
  void clear_pcd_path();
  static const int kPcdPathFieldNumber = 1;
  const ::std::string& pcd_path() const;
  void set_pcd_path(const ::std::string& value);
  #if LANG_CXX11
  void set_pcd_path(::std::string&& value);
  #endif
  void set_pcd_path(const char* value);
  void set_pcd_path(const char* value, size_t size);
  ::std::string* mutable_pcd_path();
  ::std::string* release_pcd_path();
  void set_allocated_pcd_path(::std::string* pcd_path);

  // int32 state = 2;
  void clear_state();
  static const int kStateFieldNumber = 2;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:xsproto.communication.PathNetInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr pcd_path_;
  ::google::protobuf::int32 state_;
  mutable int _cached_size_;
  friend struct ::protobuf_business_2fpath_5fnet_5finfo_2eproto::TableStruct;
  friend void ::protobuf_business_2fpath_5fnet_5finfo_2eproto::InitDefaultsPathNetInfoImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PathNetInfo

// string pcd_path = 1;
inline void PathNetInfo::clear_pcd_path() {
  pcd_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PathNetInfo::pcd_path() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.PathNetInfo.pcd_path)
  return pcd_path_.GetNoArena();
}
inline void PathNetInfo::set_pcd_path(const ::std::string& value) {
  
  pcd_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:xsproto.communication.PathNetInfo.pcd_path)
}
#if LANG_CXX11
inline void PathNetInfo::set_pcd_path(::std::string&& value) {
  
  pcd_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xsproto.communication.PathNetInfo.pcd_path)
}
#endif
inline void PathNetInfo::set_pcd_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  pcd_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xsproto.communication.PathNetInfo.pcd_path)
}
inline void PathNetInfo::set_pcd_path(const char* value, size_t size) {
  
  pcd_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xsproto.communication.PathNetInfo.pcd_path)
}
inline ::std::string* PathNetInfo::mutable_pcd_path() {
  
  // @@protoc_insertion_point(field_mutable:xsproto.communication.PathNetInfo.pcd_path)
  return pcd_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PathNetInfo::release_pcd_path() {
  // @@protoc_insertion_point(field_release:xsproto.communication.PathNetInfo.pcd_path)
  
  return pcd_path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PathNetInfo::set_allocated_pcd_path(::std::string* pcd_path) {
  if (pcd_path != NULL) {
    
  } else {
    
  }
  pcd_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pcd_path);
  // @@protoc_insertion_point(field_set_allocated:xsproto.communication.PathNetInfo.pcd_path)
}

// int32 state = 2;
inline void PathNetInfo::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 PathNetInfo::state() const {
  // @@protoc_insertion_point(field_get:xsproto.communication.PathNetInfo.state)
  return state_;
}
inline void PathNetInfo::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:xsproto.communication.PathNetInfo.state)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace communication
}  // namespace xsproto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_business_2fpath_5fnet_5finfo_2eproto__INCLUDED
