// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: perception/sync_lidar_camera_fusion_data.proto

#ifndef PROTOBUF_perception_2fsync_5flidar_5fcamera_5ffusion_5fdata_2eproto__INCLUDED
#define PROTOBUF_perception_2fsync_5flidar_5fcamera_5ffusion_5fdata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "base/header.pb.h"
#include "perception/perception_common.pb.h"
#include "perception/mono_camera_data.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_perception_2fsync_5flidar_5fcamera_5ffusion_5fdata_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSyncLidarCameraFusionDataImpl();
void InitDefaultsSyncLidarCameraFusionData();
inline void InitDefaults() {
  InitDefaultsSyncLidarCameraFusionData();
}
}  // namespace protobuf_perception_2fsync_5flidar_5fcamera_5ffusion_5fdata_2eproto
namespace xsproto {
namespace perception {
class SyncLidarCameraFusionData;
class SyncLidarCameraFusionDataDefaultTypeInternal;
extern SyncLidarCameraFusionDataDefaultTypeInternal _SyncLidarCameraFusionData_default_instance_;
}  // namespace perception
}  // namespace xsproto
namespace xsproto {
namespace perception {

// ===================================================================

class SyncLidarCameraFusionData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:xsproto.perception.SyncLidarCameraFusionData) */ {
 public:
  SyncLidarCameraFusionData();
  virtual ~SyncLidarCameraFusionData();

  SyncLidarCameraFusionData(const SyncLidarCameraFusionData& from);

  inline SyncLidarCameraFusionData& operator=(const SyncLidarCameraFusionData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SyncLidarCameraFusionData(SyncLidarCameraFusionData&& from) noexcept
    : SyncLidarCameraFusionData() {
    *this = ::std::move(from);
  }

  inline SyncLidarCameraFusionData& operator=(SyncLidarCameraFusionData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SyncLidarCameraFusionData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SyncLidarCameraFusionData* internal_default_instance() {
    return reinterpret_cast<const SyncLidarCameraFusionData*>(
               &_SyncLidarCameraFusionData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SyncLidarCameraFusionData* other);
  friend void swap(SyncLidarCameraFusionData& a, SyncLidarCameraFusionData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SyncLidarCameraFusionData* New() const PROTOBUF_FINAL { return New(NULL); }

  SyncLidarCameraFusionData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SyncLidarCameraFusionData& from);
  void MergeFrom(const SyncLidarCameraFusionData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SyncLidarCameraFusionData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes image_data = 8;
  void clear_image_data();
  static const int kImageDataFieldNumber = 8;
  const ::std::string& image_data() const;
  void set_image_data(const ::std::string& value);
  #if LANG_CXX11
  void set_image_data(::std::string&& value);
  #endif
  void set_image_data(const char* value);
  void set_image_data(const void* value, size_t size);
  ::std::string* mutable_image_data();
  ::std::string* release_image_data();
  void set_allocated_image_data(::std::string* image_data);

  // bytes lidar_data = 12;
  void clear_lidar_data();
  static const int kLidarDataFieldNumber = 12;
  const ::std::string& lidar_data() const;
  void set_lidar_data(const ::std::string& value);
  #if LANG_CXX11
  void set_lidar_data(::std::string&& value);
  #endif
  void set_lidar_data(const char* value);
  void set_lidar_data(const void* value, size_t size);
  ::std::string* mutable_lidar_data();
  ::std::string* release_lidar_data();
  void set_allocated_lidar_data(::std::string* lidar_data);

  // .xsproto.base.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::xsproto::base::Header& header() const;
  ::xsproto::base::Header* release_header();
  ::xsproto::base::Header* mutable_header();
  void set_allocated_header(::xsproto::base::Header* header);

  // .xsproto.perception.CamearaIntrinsicParameters intrinsic_params = 10;
  bool has_intrinsic_params() const;
  void clear_intrinsic_params();
  static const int kIntrinsicParamsFieldNumber = 10;
  const ::xsproto::perception::CamearaIntrinsicParameters& intrinsic_params() const;
  ::xsproto::perception::CamearaIntrinsicParameters* release_intrinsic_params();
  ::xsproto::perception::CamearaIntrinsicParameters* mutable_intrinsic_params();
  void set_allocated_intrinsic_params(::xsproto::perception::CamearaIntrinsicParameters* intrinsic_params);

  // .xsproto.perception.ExtrinsicParameters extrinsic_params = 11;
  bool has_extrinsic_params() const;
  void clear_extrinsic_params();
  static const int kExtrinsicParamsFieldNumber = 11;
  const ::xsproto::perception::ExtrinsicParameters& extrinsic_params() const;
  ::xsproto::perception::ExtrinsicParameters* release_extrinsic_params();
  ::xsproto::perception::ExtrinsicParameters* mutable_extrinsic_params();
  void set_allocated_extrinsic_params(::xsproto::perception::ExtrinsicParameters* extrinsic_params);

  // uint32 camera_type = 2;
  void clear_camera_type();
  static const int kCameraTypeFieldNumber = 2;
  ::google::protobuf::uint32 camera_type() const;
  void set_camera_type(::google::protobuf::uint32 value);

  // uint32 camera_mode = 3;
  void clear_camera_mode();
  static const int kCameraModeFieldNumber = 3;
  ::google::protobuf::uint32 camera_mode() const;
  void set_camera_mode(::google::protobuf::uint32 value);

  // uint32 width = 4;
  void clear_width();
  static const int kWidthFieldNumber = 4;
  ::google::protobuf::uint32 width() const;
  void set_width(::google::protobuf::uint32 value);

  // uint32 height = 5;
  void clear_height();
  static const int kHeightFieldNumber = 5;
  ::google::protobuf::uint32 height() const;
  void set_height(::google::protobuf::uint32 value);

  // uint32 pixel_channel = 6;
  void clear_pixel_channel();
  static const int kPixelChannelFieldNumber = 6;
  ::google::protobuf::uint32 pixel_channel() const;
  void set_pixel_channel(::google::protobuf::uint32 value);

  // uint32 image_format = 7;
  void clear_image_format();
  static const int kImageFormatFieldNumber = 7;
  ::google::protobuf::uint32 image_format() const;
  void set_image_format(::google::protobuf::uint32 value);

  // .xsproto.perception.LenMode len_mode = 9;
  void clear_len_mode();
  static const int kLenModeFieldNumber = 9;
  ::xsproto::perception::LenMode len_mode() const;
  void set_len_mode(::xsproto::perception::LenMode value);

  // @@protoc_insertion_point(class_scope:xsproto.perception.SyncLidarCameraFusionData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr image_data_;
  ::google::protobuf::internal::ArenaStringPtr lidar_data_;
  ::xsproto::base::Header* header_;
  ::xsproto::perception::CamearaIntrinsicParameters* intrinsic_params_;
  ::xsproto::perception::ExtrinsicParameters* extrinsic_params_;
  ::google::protobuf::uint32 camera_type_;
  ::google::protobuf::uint32 camera_mode_;
  ::google::protobuf::uint32 width_;
  ::google::protobuf::uint32 height_;
  ::google::protobuf::uint32 pixel_channel_;
  ::google::protobuf::uint32 image_format_;
  int len_mode_;
  mutable int _cached_size_;
  friend struct ::protobuf_perception_2fsync_5flidar_5fcamera_5ffusion_5fdata_2eproto::TableStruct;
  friend void ::protobuf_perception_2fsync_5flidar_5fcamera_5ffusion_5fdata_2eproto::InitDefaultsSyncLidarCameraFusionDataImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SyncLidarCameraFusionData

// .xsproto.base.Header header = 1;
inline bool SyncLidarCameraFusionData::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::xsproto::base::Header& SyncLidarCameraFusionData::header() const {
  const ::xsproto::base::Header* p = header_;
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncLidarCameraFusionData.header)
  return p != NULL ? *p : *reinterpret_cast<const ::xsproto::base::Header*>(
      &::xsproto::base::_Header_default_instance_);
}
inline ::xsproto::base::Header* SyncLidarCameraFusionData::release_header() {
  // @@protoc_insertion_point(field_release:xsproto.perception.SyncLidarCameraFusionData.header)
  
  ::xsproto::base::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::xsproto::base::Header* SyncLidarCameraFusionData::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::xsproto::base::Header;
  }
  // @@protoc_insertion_point(field_mutable:xsproto.perception.SyncLidarCameraFusionData.header)
  return header_;
}
inline void SyncLidarCameraFusionData::set_allocated_header(::xsproto::base::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:xsproto.perception.SyncLidarCameraFusionData.header)
}

// uint32 camera_type = 2;
inline void SyncLidarCameraFusionData::clear_camera_type() {
  camera_type_ = 0u;
}
inline ::google::protobuf::uint32 SyncLidarCameraFusionData::camera_type() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncLidarCameraFusionData.camera_type)
  return camera_type_;
}
inline void SyncLidarCameraFusionData::set_camera_type(::google::protobuf::uint32 value) {
  
  camera_type_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncLidarCameraFusionData.camera_type)
}

// uint32 camera_mode = 3;
inline void SyncLidarCameraFusionData::clear_camera_mode() {
  camera_mode_ = 0u;
}
inline ::google::protobuf::uint32 SyncLidarCameraFusionData::camera_mode() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncLidarCameraFusionData.camera_mode)
  return camera_mode_;
}
inline void SyncLidarCameraFusionData::set_camera_mode(::google::protobuf::uint32 value) {
  
  camera_mode_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncLidarCameraFusionData.camera_mode)
}

// uint32 width = 4;
inline void SyncLidarCameraFusionData::clear_width() {
  width_ = 0u;
}
inline ::google::protobuf::uint32 SyncLidarCameraFusionData::width() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncLidarCameraFusionData.width)
  return width_;
}
inline void SyncLidarCameraFusionData::set_width(::google::protobuf::uint32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncLidarCameraFusionData.width)
}

// uint32 height = 5;
inline void SyncLidarCameraFusionData::clear_height() {
  height_ = 0u;
}
inline ::google::protobuf::uint32 SyncLidarCameraFusionData::height() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncLidarCameraFusionData.height)
  return height_;
}
inline void SyncLidarCameraFusionData::set_height(::google::protobuf::uint32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncLidarCameraFusionData.height)
}

// uint32 pixel_channel = 6;
inline void SyncLidarCameraFusionData::clear_pixel_channel() {
  pixel_channel_ = 0u;
}
inline ::google::protobuf::uint32 SyncLidarCameraFusionData::pixel_channel() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncLidarCameraFusionData.pixel_channel)
  return pixel_channel_;
}
inline void SyncLidarCameraFusionData::set_pixel_channel(::google::protobuf::uint32 value) {
  
  pixel_channel_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncLidarCameraFusionData.pixel_channel)
}

// uint32 image_format = 7;
inline void SyncLidarCameraFusionData::clear_image_format() {
  image_format_ = 0u;
}
inline ::google::protobuf::uint32 SyncLidarCameraFusionData::image_format() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncLidarCameraFusionData.image_format)
  return image_format_;
}
inline void SyncLidarCameraFusionData::set_image_format(::google::protobuf::uint32 value) {
  
  image_format_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncLidarCameraFusionData.image_format)
}

// bytes image_data = 8;
inline void SyncLidarCameraFusionData::clear_image_data() {
  image_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SyncLidarCameraFusionData::image_data() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncLidarCameraFusionData.image_data)
  return image_data_.GetNoArena();
}
inline void SyncLidarCameraFusionData::set_image_data(const ::std::string& value) {
  
  image_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncLidarCameraFusionData.image_data)
}
#if LANG_CXX11
inline void SyncLidarCameraFusionData::set_image_data(::std::string&& value) {
  
  image_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xsproto.perception.SyncLidarCameraFusionData.image_data)
}
#endif
inline void SyncLidarCameraFusionData::set_image_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  image_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xsproto.perception.SyncLidarCameraFusionData.image_data)
}
inline void SyncLidarCameraFusionData::set_image_data(const void* value, size_t size) {
  
  image_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xsproto.perception.SyncLidarCameraFusionData.image_data)
}
inline ::std::string* SyncLidarCameraFusionData::mutable_image_data() {
  
  // @@protoc_insertion_point(field_mutable:xsproto.perception.SyncLidarCameraFusionData.image_data)
  return image_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SyncLidarCameraFusionData::release_image_data() {
  // @@protoc_insertion_point(field_release:xsproto.perception.SyncLidarCameraFusionData.image_data)
  
  return image_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SyncLidarCameraFusionData::set_allocated_image_data(::std::string* image_data) {
  if (image_data != NULL) {
    
  } else {
    
  }
  image_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), image_data);
  // @@protoc_insertion_point(field_set_allocated:xsproto.perception.SyncLidarCameraFusionData.image_data)
}

// .xsproto.perception.LenMode len_mode = 9;
inline void SyncLidarCameraFusionData::clear_len_mode() {
  len_mode_ = 0;
}
inline ::xsproto::perception::LenMode SyncLidarCameraFusionData::len_mode() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncLidarCameraFusionData.len_mode)
  return static_cast< ::xsproto::perception::LenMode >(len_mode_);
}
inline void SyncLidarCameraFusionData::set_len_mode(::xsproto::perception::LenMode value) {
  
  len_mode_ = value;
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncLidarCameraFusionData.len_mode)
}

// .xsproto.perception.CamearaIntrinsicParameters intrinsic_params = 10;
inline bool SyncLidarCameraFusionData::has_intrinsic_params() const {
  return this != internal_default_instance() && intrinsic_params_ != NULL;
}
inline const ::xsproto::perception::CamearaIntrinsicParameters& SyncLidarCameraFusionData::intrinsic_params() const {
  const ::xsproto::perception::CamearaIntrinsicParameters* p = intrinsic_params_;
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncLidarCameraFusionData.intrinsic_params)
  return p != NULL ? *p : *reinterpret_cast<const ::xsproto::perception::CamearaIntrinsicParameters*>(
      &::xsproto::perception::_CamearaIntrinsicParameters_default_instance_);
}
inline ::xsproto::perception::CamearaIntrinsicParameters* SyncLidarCameraFusionData::release_intrinsic_params() {
  // @@protoc_insertion_point(field_release:xsproto.perception.SyncLidarCameraFusionData.intrinsic_params)
  
  ::xsproto::perception::CamearaIntrinsicParameters* temp = intrinsic_params_;
  intrinsic_params_ = NULL;
  return temp;
}
inline ::xsproto::perception::CamearaIntrinsicParameters* SyncLidarCameraFusionData::mutable_intrinsic_params() {
  
  if (intrinsic_params_ == NULL) {
    intrinsic_params_ = new ::xsproto::perception::CamearaIntrinsicParameters;
  }
  // @@protoc_insertion_point(field_mutable:xsproto.perception.SyncLidarCameraFusionData.intrinsic_params)
  return intrinsic_params_;
}
inline void SyncLidarCameraFusionData::set_allocated_intrinsic_params(::xsproto::perception::CamearaIntrinsicParameters* intrinsic_params) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(intrinsic_params_);
  }
  if (intrinsic_params) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      intrinsic_params = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, intrinsic_params, submessage_arena);
    }
    
  } else {
    
  }
  intrinsic_params_ = intrinsic_params;
  // @@protoc_insertion_point(field_set_allocated:xsproto.perception.SyncLidarCameraFusionData.intrinsic_params)
}

// .xsproto.perception.ExtrinsicParameters extrinsic_params = 11;
inline bool SyncLidarCameraFusionData::has_extrinsic_params() const {
  return this != internal_default_instance() && extrinsic_params_ != NULL;
}
inline const ::xsproto::perception::ExtrinsicParameters& SyncLidarCameraFusionData::extrinsic_params() const {
  const ::xsproto::perception::ExtrinsicParameters* p = extrinsic_params_;
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncLidarCameraFusionData.extrinsic_params)
  return p != NULL ? *p : *reinterpret_cast<const ::xsproto::perception::ExtrinsicParameters*>(
      &::xsproto::perception::_ExtrinsicParameters_default_instance_);
}
inline ::xsproto::perception::ExtrinsicParameters* SyncLidarCameraFusionData::release_extrinsic_params() {
  // @@protoc_insertion_point(field_release:xsproto.perception.SyncLidarCameraFusionData.extrinsic_params)
  
  ::xsproto::perception::ExtrinsicParameters* temp = extrinsic_params_;
  extrinsic_params_ = NULL;
  return temp;
}
inline ::xsproto::perception::ExtrinsicParameters* SyncLidarCameraFusionData::mutable_extrinsic_params() {
  
  if (extrinsic_params_ == NULL) {
    extrinsic_params_ = new ::xsproto::perception::ExtrinsicParameters;
  }
  // @@protoc_insertion_point(field_mutable:xsproto.perception.SyncLidarCameraFusionData.extrinsic_params)
  return extrinsic_params_;
}
inline void SyncLidarCameraFusionData::set_allocated_extrinsic_params(::xsproto::perception::ExtrinsicParameters* extrinsic_params) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(extrinsic_params_);
  }
  if (extrinsic_params) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      extrinsic_params = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, extrinsic_params, submessage_arena);
    }
    
  } else {
    
  }
  extrinsic_params_ = extrinsic_params;
  // @@protoc_insertion_point(field_set_allocated:xsproto.perception.SyncLidarCameraFusionData.extrinsic_params)
}

// bytes lidar_data = 12;
inline void SyncLidarCameraFusionData::clear_lidar_data() {
  lidar_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SyncLidarCameraFusionData::lidar_data() const {
  // @@protoc_insertion_point(field_get:xsproto.perception.SyncLidarCameraFusionData.lidar_data)
  return lidar_data_.GetNoArena();
}
inline void SyncLidarCameraFusionData::set_lidar_data(const ::std::string& value) {
  
  lidar_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:xsproto.perception.SyncLidarCameraFusionData.lidar_data)
}
#if LANG_CXX11
inline void SyncLidarCameraFusionData::set_lidar_data(::std::string&& value) {
  
  lidar_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xsproto.perception.SyncLidarCameraFusionData.lidar_data)
}
#endif
inline void SyncLidarCameraFusionData::set_lidar_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  lidar_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xsproto.perception.SyncLidarCameraFusionData.lidar_data)
}
inline void SyncLidarCameraFusionData::set_lidar_data(const void* value, size_t size) {
  
  lidar_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xsproto.perception.SyncLidarCameraFusionData.lidar_data)
}
inline ::std::string* SyncLidarCameraFusionData::mutable_lidar_data() {
  
  // @@protoc_insertion_point(field_mutable:xsproto.perception.SyncLidarCameraFusionData.lidar_data)
  return lidar_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SyncLidarCameraFusionData::release_lidar_data() {
  // @@protoc_insertion_point(field_release:xsproto.perception.SyncLidarCameraFusionData.lidar_data)
  
  return lidar_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SyncLidarCameraFusionData::set_allocated_lidar_data(::std::string* lidar_data) {
  if (lidar_data != NULL) {
    
  } else {
    
  }
  lidar_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), lidar_data);
  // @@protoc_insertion_point(field_set_allocated:xsproto.perception.SyncLidarCameraFusionData.lidar_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace perception
}  // namespace xsproto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_perception_2fsync_5flidar_5fcamera_5ffusion_5fdata_2eproto__INCLUDED
